### ISSUE TITLE
Feature: custom teleport locations

### ISSUE THREAD

**Issue by mr190e** [Mirasaki/cftools-discord-bot#10]
The teleport function is very powerful as you can easily teleport players in the air (which might kill them), or teleport them out of the map. Therefor I dont want admins on our server to use that command. Instead custom teleport-locations shall be added.
On our server we have keyrooms with automated doors. Players can get stuck in there and than they open a ticket. An admin than shall be able to teleport the player out (as he tells him in the ticket in which keyroom he is) to the desired location (which will be just outside that keyroom)

In the servers config allow an array of coordinates (x,z,y) as well as a custom name of for each created location. An admin than can issue a new teleport command (/teleport-location) and than can select one of the pre-defined locations.

example:

/teleport-location: zeleno

The bot is great by the way :-)

**Comment by Mirasaki** [comment]
Hey there, and thank you for showing interest in the project ❤️ 

> The bot is great by the way :-)

Thanks a ton, I appreciate it - at the end of the day, that's what we're doing it for

Super cool feature suggestion, I have implemented this for several clients in the past and will definitely start a development branch for this

**Comment by Mirasaki** [comment]
Hmm. I can't really configure all the locations myself. We'd need a community contribution for that. I'm not very interested in release this with an empty configuration. I feel like all major towns and locations should have be in the default configuration. We can even allow customizing the config through commands. I hope you agree that it would definitely need a good list to start off with

**Comment by Mirasaki** [comment]
@mr190e Do you know about this?

> In the teleport action, if coords#y is left at 0.0 or undefined altogether, would it automatically resolve the y-level (like VPPAdminTools) or would it straight up teleport the player to y-level 0?

**Comment by Mirasaki** [comment]
Implementation is basically done in #14, but I'd like to at least have some default locations for Chernarus before releasing this

**Comment by Mirasaki** [comment]
Thanks to Frank Black for the default Chernarus locations
