### ISSUE TITLE
[BUG] - couldn't find specified resource - resource might be unknown to client, or it's invalid

### ISSUE THREAD

**Issue by AuthFailed** [Mirasaki/cftools-discord-bot#107]
**To Reproduce**
1. Use /statistics or /admin-player-list command
2. Get error couldn't find specified resource - resource might be unknown to client, or it's invalid

Also error on command broadcast: invalid response code - message might not have broadcasted

I'm already authorized application for my server on cfcloud, but nothing works. But server-info works correct

**Comment by AuthFailed** [comment]
![изображение](https://github.com/Mirasaki/cftools-discord-bot/assets/21986465/80c2b4ed-1c76-465d-ae2e-3da3a7e12df8)

**Comment by AuthFailed** [comment]
Also in configs I'm already insert all ids and tokens

**Comment by Mirasaki** [comment]
You are most likely using the wrong `Server API ID`, or an invalid combination of `Application ID` + `Secret` and `Server API ID`, please refer to [the guide](https://wiki.mirasaki.dev/docs/cftools-server-api-id) for a detailed overview of this information

**Comment by Mirasaki** [comment]
Closing this as the wiki has all the information needed to resolve this issue
