### ISSUE TITLE
[BUG] - error using statistics command

### ISSUE THREAD

**Issue by mr190e** [Mirasaki/cftools-discord-bot#11]
When using the statistics command (with a steam64) the following happens:

In discord the bot is stuck "Name-of-Bot is thinkig..."

And in log files I find this error:
```

[19:37:27] [SYSERR] : An error has occurred while executing the /statistics command

Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)

    at ChildProcess.emit (node:events:513:28)

    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

    at onErrorNT (node:internal/child_process:483:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

[19:37:27] [DEBUG]  : statistics executed in 729.84 ms
```

The error appears no matter what steamID i put in or BohemiaID

**Comment by Mirasaki** [comment]
This happens because we're trying to launch a headless chromium browser, the dependencies might not be installed.

What OS are you on, some Linux distro I'm guessing - but which one specifically?

**Comment by Mirasaki** [comment]
I have added `STATISTICS_INCLUDE_ZONES_HEATMAP` as a server config setting - you can disable this (false) to temporarily avoid trying to initialze the headless chromium instance

**Comment by Mirasaki** [comment]
Please install the Chromium dependency using `sudo apt-get install chromium-browser`

**Comment by Mirasaki** [comment]
Not technically a bug, I have to document this and add user customization for the Chromium executable path

**Comment by Mirasaki** [comment]
I have updated the documentation accordingly, please refer to: https://github.com/Mirasaki/cftools-discord-bot#prerequisites

Feel free to re-open this issue if you're still encountering issues after installing the dependency

**Comment by mr190e** [comment]
I use the bot running from a Docker container on Ubuntu 22.04 LTS

How I get Chromium in the container installed?

**Comment by Mirasaki** [comment]
Pretty quick and simple with Docker Compose, let me send you an example

**Comment by Mirasaki** [comment]
@mr190e I've updated the production and development Dockerfiles to include direct support for Chromium/Puppeteer:

https://github.com/Mirasaki/cftools-discord-bot/pull/43/files

**Comment by Mirasaki** [comment]
Let me know how it goes, I'll re-open this issue for now. Please download the latest bundle from the `main` branch, or update your Dockerfiles manually by comparing (not recommended)

**Comment by Mirasaki** [comment]
@mr190e Bump, please let me know if this works for you

**Comment by mr190e** [comment]
Hey mate, I am travelling atm. Can test it Friday Gesendet mit der mobilen Mail AppAm 06.06.23 um 16:17 schrieb Richard Hillebrand
                
            
            
                
                    Von: "Richard Hillebrand" ***@***.***>Datum: 6. Juni 2023An: "Mirasaki/cftools-discord-bot" ***@***.***>Cc: "Mention" ***@***.***>,"mr190e" ***@***.***>Betreff: Re: [Mirasaki/cftools-discord-bot] [BUG] - error using statistics command (Issue #11)
                
                
@mr190e Bump, please let me know if this works for you

**Comment by Mirasaki** [comment]
Sure thing, let me know - good luck in your travels!

**Comment by mr190e** [comment]
Doesnt work. Just build a new image and ran the /statistics command again.

This is the error:

```
[20:53:04] [SYSERR] : An error has occurred while executing the /statistics command

Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/chrome ENOENT

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)

    at ChildProcess.emit (node:events:513:28)

    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

    at onErrorNT (node:internal/child_process:483:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

[20:53:04] [DEBUG]  : statistics executed in 728.33 ms
![grafik](https://github.com/Mirasaki/cftools-discord-bot/assets/84240334/b05dc49d-38cb-439a-b235-562eb6b2eb13)

```



The built of the image was fine I'd say

**Comment by Mirasaki** [comment]
We're probably going to have to add an option to overwrite the path pointing to the Chromium executable if this doesn't work
