### ISSUE TITLE
add watch list

### ISSUE THREAD

**Issue by mr190e** [Mirasaki/cftools-discord-bot#115]
On our DayZ server, respectivly on the discord, we use a watch list which is more or less just a Discord channel with CFtools links to certain players we keep an eye out. We do this to watch players, meaning we try to go ingame and spectate to see if we can obeserve strange behaviour.

Can it be automated to have a channel where you just copy / paste the CFtools-ID and the bot warns you when that player comes online? Like this all players have the same information (CFtools offers something similiar, but every admins has to set ip up manuallay).

The notification shall ping a role, as well as the recent stats

**Comment by Mirasaki** [comment]
Hey there, thank you for your feature request - we always appreciate it when the community shows interest in the project, especially by suggestion/requesting features as you are the ones using the bot on a daily basis. 

I love the feature, I'll get this implemented and rolled out over the weekend. We'll use an in-memory database with json persistency so no additional set-up is required by the user. Unless you think the watch list might exceed thousands of entries (I'm really not sure if this is realistic) in which case we might have to add the possibility to use a SQL or Mongo adapter

**Comment by Mirasaki** [comment]
This has been implemented and will be included in the upcoming release
