### ISSUE TITLE
Feature: More teleport options

### ISSUE THREAD

**Issue by Myst-LB** [Mirasaki/cftools-discord-bot#20]
**Is your feature request related to a problem? Please describe.**
Well as in this version right now we have to input the coordinate to teleport a player manually.

**Describe the solution you'd like**
What would be nice is to have another option to teleport to a player directly:
/teleport server:`server1` player:`player1` toPlayer:`player2`

**Describe alternatives you've considered**
We could also make it into a mass teleport like :
/teleportAll players server:`server1`  toPlayer:`player2`
/teleportAll players server:`server1`  tolocation:`Berezino`
or
listing multiple players:
/teleport server:`server1` player:`player1,player2,etc` toPlayer:`player2`

**Additional context**
as admins, we sometimes would like to teleport ourselves directly to the player or vice versa, and dealing with player usernames would be more user-friendly as they are listed and autocompleted.

**Comment by Mirasaki** [comment]
First of all, thanks for your interest in the project <3
Amazing feature suggestion, will be implemented!
We also have #10 currently in development and this will be a super nice addition to that teleport functionality.

**Comment by Mirasaki** [comment]
Teleport all would teleport players on a 15 second interval, this is to account for rate limiting
