### ISSUE TITLE
[BUG] - Duration day/night in `/server-stats` cycle reportedly wrong

### ISSUE THREAD

**Issue by Mirasaki** [Mirasaki/cftools-discord-bot#32]
**Describe the bug**
The calculated duration for the day/night cycle displayed in the `/server-stats` command is wrong. User reported 6/1.2 being displayed instead of 3/45 what it should be. But, they didn't give me their time acceleration configuration - so who am I to know 🤷

Needs help as I can't really test this myself, would need someone to verify the upcoming pr fixes this 

**To Reproduce**
1. Use the `/server-stats` command and compare to your day/night cycle acceleration settings

**Additional context**
- Reported by "TRG#3954"

**Comment by Mirasaki** [comment]
Tested against documentation and confirmed accurate in pull request:
```
serverTimeAcceleration = 1;	// Accelerated Time - The numerical value being a multiplier (0.1-64). Thus, in case it is set to 24, time would move 24 times faster than normal. An entire day would pass in one hour.
serverNightTimeAcceleration = 1;// Accelerated Nigh Time - The numerical value being a multiplier (0.1-64) and also multiplied by serverTimeAcceleration value.
								// Thus, in case it is set to 4 and serverTimeAcceleration is set to 2, night time would move 8 times faster than normal.
								// An entire night would pass in 3 hours.
```

**Comment by tobiasreichel** [comment]
I'll give it a test asap
