### ISSUE TITLE
Feature: add steamid to `/admin-player-list`

### ISSUE THREAD

**Issue by Mirasaki** [Mirasaki/cftools-discord-bot#34]
**Is your feature request related to a problem? Please describe.**
Player stats are kinda pointless if I have to go to cftools to get there steamid.  So maybe on the admin player list add a players ID to the message so you can do it all in spot.

**Describe the solution you'd like**
Add steam64 to admin player-list

**Describe alternatives you've considered**
n/a

**Additional context**
- Requested by "TRG#3954"

**Comment by krussedull** [comment]
add cf id for admins that only are admins on discord and not cf aswell?

**Comment by Mirasaki** [comment]
It only checks the Discord permission
