### ISSUE TITLE
Feature: Discord > DayZ Chat - RCON Colorization Support

### ISSUE THREAD

**Issue by PlaygroundServers** [Mirasaki/cftools-discord-bot#50]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In March of 2023, CFTools added support for RCON Colorization using `|>C{hex}` to messages which would change the color of messages sent to discord to the corresponding hex color. This would allow users to customize the color of the messages they want to send from discord to that of which they want. 

**Example Item**
`|>Cadd8e6Server Admin: Server will be shutting down in 15 minutes for updates!` would print in light blue in the dayz server text.

**Comment by tobiasreichel** [comment]
Server.js

{
        roleIds: clientConfig.permissions.moderatorRoleIds,
        displayTag: '[MOD],
        displayColor:  clientConfig.Color.Blue
      },



Color.js


{
  "main": "#ffffff",
  "invisible": "#36393f",
  "success": "#00b105",
  "error": "#d91d1d",
  "red": "#FF0000",
  "blue": "#00FFFF"
}

**Comment by PlaygroundServers** [comment]
when calling it does not use the `#` so that would be the difference.

**Comment by tobiasreichel** [comment]
#56

**Comment by Mirasaki** [comment]
Implemented, thanks @tobiasreichel - chad 💪
