### ISSUE TITLE
[BUG] - teleport-to-player

### ISSUE THREAD

**Issue by mr190e** [Mirasaki/cftools-discord-bot#61]
**Describe the bug**
not sure if it is a bug or a feature :-D
Using the teleport-to-player command will teleport you to the location where the target player joined the game - not to his actual position. 

**To Reproduce**
1. just port to a player who moved from his join location

**Expected behavior**
not sure if it is intended, but if so the command should be like teleport-to-last-player-login-location or so

**Comment by tobiasreichel** [comment]
we are aware of this problem and problably will remove that function for now untill cftools gives us the prober api content

cause cftools does not update the the api to the latest player cords

**Comment by Mirasaki** [comment]
Exactly, Tobias was kind enough to make a feature suggestion to CFTools which you can track here: https://canary.discord.com/channels/373098389174484992/776006893956628491/1115381615212888064

Please upvote this feature suggestions, if we can 25+ upvotes it will be hard for them to ignore the feature requests. It's a major feature for a bot like this.

**Comment by Mirasaki** [comment]
This has been addressed by CFTools: https://canary.discord.com/channels/373098389174484992/865686257111924777/1131290482501226526
![DiscordCanary_gUD2REr6Bj](https://github.com/Mirasaki/cftools-discord-bot/assets/57721238/53689ec9-a746-4f7b-be86-d77fdb0ca65d)
